Add hotkeys
dennis-tra/alfred-dict.cc-workflow pull request #13
Opened 2022-10-23 16:52 UTC by muffix

Adds keyboard hotkeys to trigger the workflow for the current selection
or the clipboard contents. Also adds a universal action trigger if the
selection is text (as opposed to file or URL).

The keyboard shortcuts are not part of the `info.plist` and even if they
were, they would be ignored when imported.

To do that, I first added the existing `info.plist` from the [latest release](https://github.com/dennis-tra/alfred-dict.cc-workflow/releases/tag/2.0.0). 6b721f3 has the interesting changes.

Relates to: #12

2022-11-04 10:35 UTC, dennis-tra requested changes

2022-11-04 10:35 UTC, dennis-tra commented on assets/info.plist
> +				<true/>
> Also adds a universal action trigger if the
selection is text (as opposed to file or URL).

For me, the universal action was available for files and URLs. I think `acceptpsurls` and `acceptsfiles` need to be changed to `false` :)

2022-11-04 10:36 UTC, dennis-tra commented
So cool, I actually didn't use the Universal Actions feature of Alfred at all! So handy :)

Thanks for the contribution! Besides my comment above this looks good to me 👍 I will definitely use this :D

2023-10-02 19:48 UTC, muffix commented
Apologies, I only saw your comment now. Addressed the issue in 44e6115.

2023-10-03 07:54 UTC, merged